runtime: nodejs16  # or another supported version

instance_class: F2  # Default F1

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
  - url: /stylesheets
    static_dir: stylesheets

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

error_handlers:
  - file: default_error.html

  - error_code: over_quota
    file: over_quota.html
